char *CONNECT_MESSAGE = "Hello! Welcome to chat.";
char *DEFAULT_NAME = "NONAME";
char *DEFAULT_CHANNEL = "NOCHANNEL";
int MAX_CHANNELS = 1000;

char INITIAL_CHANNELS[][20] = {};
int LEN_INITIAL_CHANNELS = 0;

char *RESPONSE_OK = "RESPONSE_OK";
